### ISSUE TITLE
index.html: update deadline for window 2 in box

### ISSUE THREAD

**Issue by kaquino** [dc-coder/gpp-mdtf#12]
`[Call for Expressions of Interest for Window 2: Country ](http://w0lxocdsdev01.worldbank.org/gpp-mdtf/docs/GPP.MDTF.Window.2.Call.for.Expressions.of.Interest.docx)`is now open! Deadline for EOIs has been extended until August 24, 2017. 

(Everything else is the same)

**Comment by kaquino** [comment]
Also add link to country.html (Call for Expressions of Interest for Window 2: Country) in box

**Comment by dc-coder** [comment]
![screen shot 2017-07-21 at 3 24 39 pm](https://user-images.githubusercontent.com/521705/28463378-c17b1484-6e28-11e7-9370-2082fa379b0b.png)

please re-open if something doesn't look good.

**Comment by dc-coder** [comment]
This has been updated to August 10 as per message from marcella on Whatsapp
