### ISSUE TITLE
Database connection error

### ISSUE THREAD

**Issue by kaquino** [dc-coder/gpp-mdtf#19]

**Comment by kaquino** [comment]
Can’t select database
We were able to connect to the database server (which means your username and password is okay) but not able to select the wbgov database.

Are you sure it exists?
Does the user root have permission to use the wbgov database?
On some systems the name of your database is prefixed with your username, so it would be like username_wbgov. Could that be the problem?
If you don’t know how to set up a database you should contact your host. If all else fails you may find help at the WordPress Support Forums.

**Comment by dc-coder** [comment]
fixed
