### ISSUE TITLE
Add event announcement for Information session

### ISSUE THREAD

**Issue by kaquino** [dc-coder/gpp-mdtf#3]
July 4 10-11am J4 101

(How do I include an RSVP link?)

**Comment by dc-coder** [comment]
should we do this before we leave on mission? (i will be on vacation after)

let me know if you have the RSVP link

**Comment by kaquino** [comment]
I am waiting for IT support to get back to me, but yes we should announce
it today either way (with RSVP or no RSVP).

Kristina
