### ISSUE TITLE
index and country: add file

### ISSUE THREAD

**Issue by kaquino** [dc-coder/gpp-mdtf#5]
Need to upload file from info session
[information session.pdf](https://github.com/dc-coder/gpp-mdtf/files/1128385/information.session.pdf)

**Comment by dc-coder** [comment]
I added on the homepage link with the title "Information Session for Window 2: Country"

On the country, i added link with the title "Information Session" (because it is more obvious)

let me know if this is ok :) - i see you already added the doc to github
