### ISSUE TITLE
main: revise event box

### ISSUE THREAD

**Issue by kaquino** [dc-coder/gpp-mdtf#6]

**Comment by dc-coder** [comment]
is there a specific text that I should put there?

**Comment by kaquino** [comment]
Call for Expressions of Interest for Window 2: Country is now open! Deadline for EOIs is July 17, 2017. Send completed forms to kaquino@worldbank.org and mrozo@worldbank.org .

Proposals for [Window 1](global.html) and [Window 3](knowledge.html) are considered on a rolling basis.

**Comment by dc-coder** [comment]
preview link generated by github is on http://dc-coder.com/gpp-mdtf/

if all is ok, please close the issue
