### ISSUE TITLE
changing the menu

### ISSUE THREAD

**Issue by dc-coder** [dc-coder/gpp-mdtf#7]
I think the default menu that came with the world bank header is too confusing.

We should

1- trim the menu by removing the navigation and leaving the world bank logo only (it is the old menu anyway and not the updated worldbank.org one anyway) 

or 

2- replace the navigation or menu by our own structure

or

3- leave menu as is, but add clear headers or navigation buttons, especially for homepage.

@kaquino , let me know what you think

**Comment by kaquino** [comment]
Option  2 sounds good to me. It is better to have MDTF Home and such up there rather than unrelated menu

**Comment by dc-coder** [comment]
Does this menu work? 

![screen shot 2017-07-11 at 4 31 27 pm](https://user-images.githubusercontent.com/521705/28070671-6e54ab64-6656-11e7-8073-6d2afc310e0b.png)

**Comment by dc-coder** [comment]
is this menu ok? any updates needed?

Feel free to close ticket or suggest new text

**Comment by dc-coder** [comment]
I did a little tweak and added numbering to each window in the menu.

**Comment by dc-coder** [comment]
Menu was updated. Issue is no longer relevant to the new worpdress version
