### ISSUE TITLE
index.html: Remove Window-Specific

### ISSUE THREAD

**Issue by kaquino** [dc-coder/gpp-mdtf#9]
Remove Window-specific criteria table (we may need later) for now

**Comment by kaquino** [comment]
*Window-specific timeline

I committed a change in Edits branch (not sure if this is right way to do it? I did not want to break anything). If right, please pull to Master (am I saying this correctly...).

**Comment by dc-coder** [comment]
It is the very correct way to do it and you've use the correct vocab.

You do changes on the edits branch and the I preview the changes and merge them to master if all is ok.

Btw you can preview your edits using rawgit.com - here is the link https://rawgit.com/dc-coder/gpp-mdtf/Edits/index.html (as you can see it points to the index page on your Edits branch)
